require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - context
        - describe
        - wrap_context
      Skipped:
        - xcontext
        - xdescribe
        - xwrap_context
      Focused:
        - fcontext
        - fdescribe
        - fwrap_context
    Includes:
      Examples:
        - finclude_contract
        - finclude_examples
        - fwrap_examples
        - include_contract
        - include_examples
        - wrap_examples
        - xinclude_contract
        - xinclude_examples
        - xwrap_examples

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  AllowedPatterns:
    - '\A\s*#'
  Max: 80

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - spec/**/*

Naming/MethodParameterName:
  AllowedNames:
    - as
    - to

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

RSpec/BeNil:
  Enabled: false

RSpec/Eq:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: example

RSpec/LeadingSubject:
  Enabled: false # Does not support shared contexts/examples before subject.

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/AccessorGrouping:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NestedParenthesizedCalls:
  Exclude:
    - spec/**/*.rb
