# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Enabled: true
  Max: 80

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - spec/**/*

Naming/MethodParameterName:
  AllowedNames:
    - as
    - to

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: example

RSpec/LeadingSubject:
  Enabled: false # Does not support shared contexts/examples before subject.

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/AccessorGrouping:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NestedParenthesizedCalls:
  Exclude:
    - spec/**/*.rb
