# Build Options
language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0
before_script:
  - cp .rspec.example .rspec
script:
  - DEPRECATION_STRATEGY=ignore bundle exec thor ci:steps

# Travis-CI Configuration
cache: bundler
sudo:  false # Enable containerized builds.
