---
name: SleepingKingStudios::Tools::Version::BUILD
parent_path: sleeping-king-studios/tools/version
slug: build
short_description: Build metadata.
value: '0'
data_path: sleeping-king-studios/tools/version/build
version: "*"
